import Footers from "@/components/molecules/Footers";
import Header from "@/components/molecules/Header";
import Contact from "@/components/sections/Contact";
import ProductCatalogue from "@/components/sections/ProductCatalogue";
import ProductHero from "@/components/sections/ProductHero";
import ProductList from "@/components/sections/ProductList";
import VideoPlaceholderProduct from "@/components/sections/VideoPlaceholderProduct";
import Head from "next/head";
import React from "react";

export default function product() {
  return (
    <>
      <Head>
        <title>Sea Cart by Solutee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/article-list/Main Logo.png" />
      </Head>
      <Header />
      <ProductHero />

      <ProductList />
      <VideoPlaceholderProduct />
      <ProductCatalogue />

      <Footers />
    </>
  );
}
