import Footers from '@/components/molecules/Footers';
import Header from '@/components/molecules/Header';
import ArticleList from '@/components/sections/ArticleList';
import DocumentasiKegiatan from '@/components/sections/DocumentasiKegiatan';
import HeroBanner from '@/components/sections/HeroBanner';
import PartnerList from '@/components/sections/PartnerList';
import ShowCaseProduct from '@/components/sections/ShowCaseProduct';
import VideoPlaceholder from '@/components/sections/VideoPlaceholder';
import WhatWeServe from '@/components/sections/WhatWeServe';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sea Cart by Solutee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/article-list/Main Logo.png" />
      </Head>
      <main className='lg:snap-container'>
        <Header />
        <div className='lg:snap-child'>

      <HeroBanner />
        </div>
        <div className=' lg:snap-child'>

      <WhatWeServe />
        </div>
        <div className=' lg:snap-child'>

      <VideoPlaceholder />
        </div>
        <div className=' lg:snap-child'>

      <ShowCaseProduct />
        </div>
        <div className=' lg:snap-child'>
      <PartnerList />

        </div>
        <div className='lg:snap-child'>

      <DocumentasiKegiatan />
        </div>
        <div className='snap-child'>

      <ArticleList />
        </div>

        <div className='snap-child'>

      <Footers />        
        </div>
      </main>

    </>
  );
}
