import Footers from '@/components/molecules/Footers';
import Header from '@/components/molecules/Header';
import ArticleList from '@/components/sections/ArticleList';
import DocumentasiKegiatan from '@/components/sections/DocumentasiKegiatan';
import HeroBanner from '@/components/sections/HeroBanner';
import NewComp from '@/components/sections/NewComp';
import PartnerList from '@/components/sections/PartnerList';
import ShowCaseProduct from '@/components/sections/ShowCaseProduct';
import VideoPlaceholder from '@/components/sections/VideoPlaceholder';
import WhatWeServe from '@/components/sections/WhatWeServe';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sea Cart by Solutee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/article-list/Main Logo.png" />
      </Head>
      <main>
      <Header />
      <HeroBanner />
      <WhatWeServe />
      <VideoPlaceholder />
      <ShowCaseProduct />
      <PartnerList />
      <DocumentasiKegiatan />
      <ArticleList />

      <Footers />        
      </main>

    </>
  );
}
