import Footers from "@/components/molecules/Footers";
import Header from "@/components/molecules/Header";
import ProductDetailContent from "@/components/sections/ProductDetailContent";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { ProductDetailData, ProductSlider } from "../../../../service/DummyData";
import Head from "next/head";

interface Props {
  id: number;
  productName: string;
  description: string;
  featureImageCollage: { id: number; url: string }[];
  featuredImageURL: string;
  images: {
    id: number;
    url: string;
    imageTitle: string;
    weight: any;
    package: any;
  }[];
}

export default function ProductDetail() {
  const router = useRouter();
  const id: string | undefined = router.query?.id as string | undefined;
  const [product, setProduct] = useState<Props | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      if (id) {
        // Simulate API call with a delay
        setTimeout(() => {
          const productData = ProductDetailData.find(
            (item) => item.id === Number(id)
          );
          setProduct(productData || null);
        }, 1000);
      }
    };

    if (id) {
      fetchData();
    }
  }, [id]);

  if (!product) {
    return <p>Loading Your Data ... </p>;
  }

  return (
    <>
      <Head>
        <title>{ product?.productName} - SeaCart </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/article-list/Main Logo.png" />
      </Head>
      <main className={``}>
        <Header />

        {product ? (
          <ProductDetailContent product={product} />
        ) : (
          <p>Loading...</p>
        )}

        <Footers />
      </main>
    </>
  );
}
